# generated by datamodel-codegen:
#   filename:  patreon-openapi.json
#   timestamp: 2026-03-08T23:02:31+00:00

from __future__ import annotations

from pydantic import AnyUrl, AwareDatetime, BaseModel, Field


class Campaign(BaseModel):
    vanity: str | None = Field(None, description="The campaign's vanity name")
    url: AnyUrl | None = Field(None, description="The url to visit this campaign")
    thanks_video_url: AnyUrl | None = Field(
        None,
        description="The URL of the video that is shown to patrons after pledging",
    )
    thanks_msg: str | None = Field(
        None, description="The message that is shown to patrons after pledging"
    )
    thanks_embed: str | None = Field(
        None, description="The embed that is shown to patrons after pledging"
    )
    summary: str | None = Field(
        None,
        description="The summary of this campaign.\nCan be viewed in the About section of the campaign",
    )
    show_earnings: bool | None = Field(
        None, description="Whether the campaign's total earnings are shown publicly"
    )
    rss_feed_title: str | None = Field(
        None, description="The title of the campaigns rss feed"
    )
    rss_artwork_url: AnyUrl | None = Field(
        None, description="The url for the rss album artwork"
    )
    published_at: AwareDatetime | None = Field(
        None,
        description="Datetime that the creator most recently published (made publicly visible) the campaign.\nNull when the campaign has not been public.",
    )
    pledge_url: str | None = Field(
        None,
        description="Relative (to patreon.com) URL for the pledge checkout flow for this campaign",
    )
    pay_per_name: str | None = Field(
        None,
        description='The thing which patrons are paying per, as in "{@link Campaign.vanity} is making $1000 per {@link Campaign.pay_per_name}"',
    )
    patron_count: float | None = Field(
        None, description="Number of patrons having access to this creator"
    )
    one_liner: str | None = Field(
        None,
        description="Pithy one-liner for this campaign, displayed on the creator page",
    )
    main_video_url: AnyUrl | None = Field(None, description="")
    main_video_embed: str | None = Field(None, description="")
    is_nsfw: bool | None = Field(
        None,
        description="Whether the creator has marked the campaign as containing nsfw content",
    )
    is_monthly: bool | None = Field(
        None, description="Whether the campaign charges per month"
    )
    is_charged_immediately: bool | None = Field(
        None, description="Whether the campaign charges upfront"
    )
    image_url: AnyUrl | None = Field(
        None, description="Banner image URL for the campaign"
    )
    image_small_url: AnyUrl | None = Field(
        None, description="Profile image URL for the campaign"
    )
    has_sent_rss_notify: bool | None = Field(
        None,
        description="Whether the creator has sent a one-time rss notification email",
    )
    has_rss: bool | None = Field(
        None, description="Whether this user has opted-in to rss feeds"
    )
    google_analytics_id: str | None = Field(
        None,
        description="The ID of the Google Analytics tracker that the creator wants metrics to be sent to",
    )
    discord_server_id: str | None = Field(
        None,
        description="The ID of the external discord server that is linked to this campaign",
    )
    creation_name: str | None = Field(
        None,
        description='The type of content the creator is creating, as in "{@link Campaign.vanity} is creating {@link Campaign.creation_name}"',
    )
    created_at: AwareDatetime | None = Field(
        None,
        description="Datetime that the creator first began the campaign creation process",
    )
