# generated by datamodel-codegen:
#   filename:  patreon-openapi.json
#   timestamp: 2026-03-08T23:02:31+00:00

from __future__ import annotations

from pydantic import AnyUrl, BaseModel, Field


class Client(BaseModel):
    author_name: str | None = Field(
        None, description="The author name provided during client setup."
    )
    category: str | None = Field(None, description="")
    client_secret: str | None = Field(None, description="The client's secret.")
    default_scopes: str | None = Field(
        None,
        description="The client's default OAuth scopes for the authorization flow.",
    )
    description: str | None = Field(
        None, description="The description provided during client setup."
    )
    domain: AnyUrl | None = Field(
        None, description="The domain provided during client setup."
    )
    icon_url: AnyUrl | None = Field(
        None, description="The URL of the icon used in the OAuth authorization flow."
    )
    name: str | None = Field(None, description="The name provided during client setup.")
    privacy_policy_url: AnyUrl | None = Field(
        None,
        description="The URL of the privacy policy provided during client setup.",
    )
    redirect_uris: str | None = Field(
        None,
        description="The allowable redirect URIs for the OAuth authorization flow.",
    )
    tos_url: AnyUrl | None = Field(
        None,
        description="The URL of the terms of service provided during client setup.",
    )
    version: float | None = Field(
        None,
        description="The Patreon API version the client is targeting.",
        examples=[2],
    )
