# generated by datamodel-codegen:
#   filename:  patreon-openapi.json
#   timestamp: 2026-03-08T23:02:31+00:00

from __future__ import annotations

from typing import Literal

from pydantic import AwareDatetime, BaseModel, Field


class Deliverable(BaseModel):
    completed_at: AwareDatetime | None = Field(
        None,
        description="When the creator marked the deliverable as completed or fulfilled to the patron",
    )
    delivery_status: Literal["delivered", "not_delivered", "wont_deliver"] | None = (
        Field(None, description="")
    )
    due_at: AwareDatetime | None = Field(
        None, description="When the deliverable is due to the patron"
    )
