# generated by datamodel-codegen:
#   filename:  patreon-openapi.json
#   timestamp: 2026-03-08T23:02:31+00:00

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel


class JSONAPIResource(BaseModel):
    type: Literal[
        "address",
        "benefit",
        "campaign",
        "client",
        "deliverable",
        "goal",
        "media",
        "member",
        "post",
        "pledge-event",
        "tier",
        "user",
        "webhook",
    ]
    id: str
