# generated by datamodel-codegen:
#   filename:  patreon-openapi.json
#   timestamp: 2026-03-08T23:02:31+00:00

from __future__ import annotations

from jsonapierror import JSONAPIError


class JSONAPIRatelimitError(JSONAPIError):
    retry_after_seconds: float | None
