# generated by datamodel-codegen:
#   filename:  patreon-openapi.json
#   timestamp: 2026-03-08T23:02:31+00:00

from __future__ import annotations

from typing import Any

from pydantic import AnyUrl, AwareDatetime, BaseModel, Field


class Media(BaseModel):
    created_at: AwareDatetime | None = Field(
        None, description="When the file was created"
    )
    download_url: AnyUrl | None = Field(
        None, description="The URL to download this media. Valid for 24 hours."
    )
    file_name: str | None = Field(None, description="File name.")
    image_urls: dict[str, Any] | None = Field(
        None, description="The resized image URLs for this media. Valid for 2 weeks."
    )
    metadata: dict[str, Any] | None = Field(
        None, description="Metadata related to the file"
    )
    mimetype: str | None = Field(
        None, description='Mimetype of uploaded file, eg: "application/jpeg"'
    )
    owner_id: str | None = Field(
        None, description="Ownership id (See also {@link Media.owner_type})"
    )
    owner_relationship: str | None = Field(
        None, description="Ownership relationship type for multi-relationship medias"
    )
    owner_type: str | None = Field(
        None, description="Type of the resource that owns the file"
    )
    size_bytes: float | None = Field(None, description="")
    state: str | None = Field(None, description="")
    upload_expires_at: AwareDatetime | None = Field(
        None, description="When the upload URL expires"
    )
    upload_parameters: dict[str, Any] | None = Field(
        None,
        description="All the parameters that have to be added to the upload form request",
    )
    upload_url: AnyUrl | None = Field(
        None,
        description="The URL to perform a POST request to in order to upload the media file",
    )
