# generated by datamodel-codegen:
#   filename:  patreon-openapi.json
#   timestamp: 2026-03-08T23:02:31+00:00

from __future__ import annotations

from typing import Literal

from pydantic import AwareDatetime, BaseModel, Field


class Member(BaseModel):
    campaign_lifetime_support_cents: float | None = Field(
        None,
        description="The total amount that the member has ever paid to the campaign in the campaign's currency.\n0 if never paid",
    )
    currently_entitled_amount_cents: float | None = Field(
        None,
        description="The amount in cents that the member is entitled to.\nThis includes a current pledge, or payment that covers the current payment period",
    )
    email: str | None = Field(
        None,
        description="The member's email address.\nRequires the campaigns.members[email] scope",
    )
    full_name: str | None = Field(
        None, description="Full name of the member user", examples=["John Doe"]
    )
    is_follower: bool | None = Field(
        None,
        description="The user is not a pledging patron but has subscribed to updates about public posts.\nThis will always be false, following has been replaced by free membership.",
    )
    is_free_trial: bool | None = Field(
        None, description="The user is in a free trial period."
    )
    is_gifted: bool | None = Field(
        None, description="The user's membership is from a free gift"
    )
    last_charge_date: AwareDatetime | None = Field(
        None,
        description="Datetime of last attempted charge.\n`null` if never charged",
    )
    last_charge_status: (
        Literal[
            "Paid",
            "Declined",
            "Deleted",
            "Pending",
            "Refunded",
            "Refunded by Patreon",
            "Partially Refunded",
            "Fraud",
            "Free Trial",
            "Other",
        ]
        | None
    ) = Field(
        None,
        description="The result of the last attempted charge.\nThe only successful status is `'Paid'`.\n`null` if never charged\n\nNote: this will likely be either `'Paid'` or `'Pending'`",
    )
    lifetime_support_cents: float | None = Field(
        None,
        description="The total amount that the member has ever paid to the campaign in the campaign's currency.\n0 if never paid.\n\nUse {@link campaign_lifetime_support_cents}.",
    )
    next_charge_date: AwareDatetime | None = Field(
        None,
        description="Datetime of next charge.\n`null` if annual pledge downgrade",
    )
    note: str | None = Field(None, description="The creator's notes on the member")
    patron_status: (
        Literal["active_patron", "declined_patron", "former_patron"] | None
    ) = Field(None, description="A `null` value indicates the member has never pledged")
    pledge_cadence: float | None = Field(
        None,
        description="Number of months between charges\n\nNote: this will be `1` if Campaign.is_monthly is `true`",
        examples=[1],
    )
    pledge_relationship_start: AwareDatetime | None = Field(
        None,
        description="Datetime of beginning of most recent pledge chainfrom this member to the campaign.\nPledge updates do not change this value",
    )
    will_pay_amount_cents: float | None = Field(
        None,
        description="The amount in cents the user will pay at the next pay cycle",
        examples=[500],
    )
