# generated by datamodel-codegen:
#   filename:  patreon-openapi.json
#   timestamp: 2026-03-08T23:02:31+00:00

from __future__ import annotations

from typing import Literal

from pydantic import AwareDatetime, BaseModel, Field


class PledgeEvent(BaseModel):
    amount_cents: float | None = Field(
        None,
        description="Amount (in the currency in which the patron paid) of the underlying event",
        examples=[500],
    )
    currency_code: str | None = Field(
        None, description="ISO code of the currency of the event"
    )
    date: AwareDatetime | None = Field(
        None, description="The date which this event occurred"
    )
    pledge_payment_status: (
        Literal["queued", "pending", "valid", "declined", "fraud", "disabled"] | None
    ) = Field(None, description="The payment status of the pledge")
    payment_status: (
        Literal[
            "Paid",
            "Declined",
            "Deleted",
            "Pending",
            "Refunded",
            "Refunded by Patreon",
            "Partially Refunded",
            "Fraud",
            "Free Trial",
            "Other",
        ]
        | None
    ) = Field(None, description="Status of underlying payment")
    tier_id: str | None = Field(
        None, description="Id of the tier associated with the pledge"
    )
    tier_title: str | None = Field(
        None, description="Title of the reward tier associated with the pledge"
    )
    type: (
        Literal[
            "pledge_start",
            "pledge_upgrade",
            "pledge_downgrade",
            "pledge_delete",
            "subscription",
        ]
        | None
    ) = Field(None, description="Event type.")
