# generated by datamodel-codegen:
#   filename:  patreon-openapi.json
#   timestamp: 2026-03-08T23:02:31+00:00

from __future__ import annotations

from typing import Any

from pydantic import AnyUrl, AwareDatetime, BaseModel, Field


class Post(BaseModel):
    app_id: float | None = Field(None, description="Platform app id")
    app_status: str | None = Field(None, description="Processing status of the post")
    content: str | None = Field(None, description="Post content, may include html tags")
    embed_data: dict[str, Any] | None = Field(
        None,
        description="An object containing embed data if media is embedded in the post",
    )
    embed_url: AnyUrl | None = Field(None, description="Embed media url")
    is_paid: bool | None = Field(
        None,
        description="Whether the post incurs a bill as part of a pay-per-post campaign",
    )
    is_public: bool | None = Field(
        None,
        description="- `true` if the post is viewable by anyone\n- `false` if only patrons (or a subset of patrons) can view",
    )
    published_at: AwareDatetime | None = Field(
        None,
        description="Datetime that the creator most recently published (made publicly visible) the post",
    )
    tiers: list[str] | None = Field(
        None,
        description="The tier ids that the post is locked for if only patrons (or a subset of patrons) can view.",
    )
    title: str | None = Field(None, description="")
    url: AnyUrl | None = Field(
        None, description="A URL to access this post on patreon.com"
    )
