# generated by datamodel-codegen:
#   filename:  patreon-openapi.json
#   timestamp: 2026-03-08T23:02:31+00:00

from __future__ import annotations

from pydantic import AnyUrl, AwareDatetime, BaseModel, Field


class Tier(BaseModel):
    amount_cents: float | None = Field(
        None, description="Monetary amount associated with this tier (in U.S. cents)"
    )
    created_at: AwareDatetime | None = Field(
        None, description="Datetime this tier was created"
    )
    description: str | None = Field(None, description="Tier display description")
    discord_role_ids: list[str] | None = Field(
        None, description="The discord role IDs granted by this tier"
    )
    edited_at: AwareDatetime | None = Field(
        None, description="Datetime tier was last modified"
    )
    image_url: AnyUrl | None = Field(
        None, description="Full qualified image URL associated with this tier"
    )
    patron_count: float | None = Field(
        None, description="Number of patrons currently registered for this tier"
    )
    post_count: float | None = Field(
        None, description="Number of posts published to this tier"
    )
    published: bool | None = Field(
        None, description="Whether the tier is currently published"
    )
    published_at: AwareDatetime | None = Field(
        None, description="Datetime this tier was last published"
    )
    remaining: float | None = Field(
        None,
        description="Remaining number of patrons who may subscribe, if there is a {@link Tier.user_limit}",
    )
    requires_shipping: bool | None = Field(
        None, description="Whether this tier requires a shipping address from patrons"
    )
    title: str | None = Field(None, description="Tier display title")
    unpublished_at: AwareDatetime | None = Field(
        None, description="Datetime tier was unpublished, while applicable"
    )
    url: AnyUrl | None = Field(
        None, description="Fully qualified URL associated with this tier"
    )
    user_limit: float | None = Field(
        None,
        description="Maximum number of patrons this tier is limited to, if applicable",
    )
