# generated by datamodel-codegen:
#   filename:  patreon-openapi.json
#   timestamp: 2026-03-08T23:02:31+00:00

from __future__ import annotations

from typing import Any

from pydantic import AnyUrl, AwareDatetime, BaseModel, EmailStr, Field


class User(BaseModel):
    about: str | None = Field(
        None, description="The user's about text, which appears on their profile"
    )
    can_see_nsfw: bool | None = Field(
        None, description="Whether this user can view nsfw content"
    )
    created: AwareDatetime | None = Field(
        None, description="Datetime of this user's account creation"
    )
    email: EmailStr | None = Field(
        None,
        description="The user's email address.\nRequires certain scopes to access.\nSee the scopes section of the documentation",
    )
    first_name: str | None = Field(None, description="First name.")
    full_name: str | None = Field(None, description="Combined first and last name")
    hide_pledges: bool | None = Field(
        None,
        description="Whether the user has chosen to keep private which creators they pledge to",
    )
    image_url: AnyUrl | None = Field(
        None, description="The user's profile picture URL, scaled to width 400px"
    )
    is_creator: bool | None = Field(
        None, description="Whether this user has an active campaign."
    )
    is_email_verified: bool | None = Field(
        None, description="Whether the user has confirmed their email"
    )
    last_name: str | None = Field(None, description="Last name.")
    like_count: float | None = Field(
        None, description="How many posts this user has liked"
    )
    social_connections: dict[str, Any] | None = Field(
        None,
        description="Mapping from user's connected app names to external user id on the respective app\n\nNOTE: since the documentation is `object`, this can change without notice.\nFor a more accurate representation use the following type using TypeScript module augmentation:\n```ts\nimport 'patreon-api.ts'\ndeclare module 'patreon-api.ts' {\n   interface CustomTypeOptions {\n       social_connections: Record<string, { url: string, user_id: string } | null>\n   }\n}\n```",
    )
    thumb_url: AnyUrl | None = Field(
        None,
        description="The user's profile picture URL, scaled to a square of size 100x100px",
    )
    url: AnyUrl | None = Field(
        None, description="URL of this user's creator or patron profile"
    )
    vanity: str | None = Field(
        None,
        description='The public "username" of the user.\npatreon.com/ goes to this user\'s creator page.\nNon-creator users might not have a vanity.',
    )
