# generated by datamodel-codegen:
#   filename:  patreon-openapi.json
#   timestamp: 2026-03-08T23:02:31+00:00

from __future__ import annotations

from pydantic import AnyUrl, AwareDatetime, BaseModel, Field


class Webhook(BaseModel):
    last_attempted_at: AwareDatetime | None = Field(
        None, description="Last date that the webhook was attempted or used."
    )
    num_consecutive_times_failed: float | None = Field(
        None,
        description="Number of times the webhook has failed consecutively, when in an error state.",
        examples=[0, 2],
    )
    paused: bool | None = Field(
        None,
        description="`true` if the webhook is paused as a result of repeated failed attempts to post to uri.\nSet to `false` to attempt to re-enable a previously failing webhook.",
    )
    secret: str | None = Field(
        None,
        description="Secret used to sign your webhook message body, so you can validate authenticity upon receipt.",
    )
    triggers: list[str] | None = Field(
        None,
        description="List of events that will trigger this webhook.",
        examples=[
            "[\n   'members:pledge:create',\n   'members:update',\n   'members:pledge:delete',\n]"
        ],
    )
    uri: AnyUrl | None = Field(
        None,
        description="Fully qualified uri where webhook will be sent",
        examples=["'https://www.example.com/webhooks/incoming'"],
    )
