# generated by datamodel-codegen:
#   filename:  patreon-openapi.json
#   timestamp: 2026-03-08T23:02:31+00:00

from __future__ import annotations

from typing import Literal

from pydantic import Field, RootModel


class WebhookTrigger(
    RootModel[
        list[
            Literal[
                "members:create",
                "members:update",
                "members:delete",
                "members:pledge:create",
                "members:pledge:update",
                "members:pledge:delete",
                "posts:publish",
                "posts:update",
                "posts:delete",
            ]
        ]
    ]
):
    root: list[
        Literal[
            "members:create",
            "members:update",
            "members:delete",
            "members:pledge:create",
            "members:pledge:update",
            "members:pledge:delete",
            "posts:publish",
            "posts:update",
            "posts:delete",
        ]
    ] = Field(
        ...,
        examples=[["members:pledge:create", "members:update", "members:pledge:delete"]],
        title="Webhook trigger",
    )
